import { describe, test, expect } from 'vitest';
import fs from 'fs';
import path from 'path';

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..', '..');

function getSourceFiles(dir, extensions = ['.js', '.jsx']) {
  const results = [];
  if (!fs.existsSync(dir)) return results;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (['node_modules', '.git', 'dist', 'coverage'].includes(entry.name)) continue;
    if (entry.isDirectory()) {
      results.push(...getSourceFiles(fullPath, extensions));
    } else if (extensions.some(ext => entry.name.endsWith(ext))) {
      results.push(fullPath);
    }
  }
  return results;
}

describe('code quality checks', () => {
  const srcFiles = [
    ...getSourceFiles(path.join(PROJECT_ROOT, 'src')),
    ...getSourceFiles(path.join(PROJECT_ROOT, 'components')),
    ...getSourceFiles(path.join(PROJECT_ROOT, 'data')),
  ];

  test('no console.log left in source code', () => {
    const violations = [];
    for (const file of srcFiles) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');
      lines.forEach((line, i) => {
        if (line.includes('console.log') && !line.trim().startsWith('//') && !line.trim().startsWith('*')) {
          violations.push(`${path.relative(PROJECT_ROOT, file)}:${i + 1}`);
        }
      });
    }
    expect(violations, `console.log found:\n${violations.join('\n')}`).toHaveLength(0);
  });

  test('no TODO or FIXME without context', () => {
    const violations = [];
    for (const file of srcFiles) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');
      lines.forEach((line, i) => {
        const match = line.match(/\/\/\s*(TODO|FIXME)\s*$/i);
        if (match) {
          violations.push(`${path.relative(PROJECT_ROOT, file)}:${i + 1}: bare ${match[1]} without description`);
        }
      });
    }
    expect(violations, violations.join('\n')).toHaveLength(0);
  });

  test('no debugger statements', () => {
    const violations = [];
    for (const file of srcFiles) {
      const content = fs.readFileSync(file, 'utf-8');
      if (/\bdebugger\b/.test(content)) {
        violations.push(path.relative(PROJECT_ROOT, file));
      }
    }
    expect(violations, `debugger found in: ${violations.join(', ')}`).toHaveLength(0);
  });

  test('no commented-out code blocks (more than 3 consecutive commented lines)', () => {
    const violations = [];
    for (const file of srcFiles) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');
      let consecutive = 0;
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim().startsWith('//') && !lines[i].trim().startsWith('// ===') && !lines[i].trim().startsWith('// ---')) {
          consecutive++;
          if (consecutive >= 5) {
            violations.push(`${path.relative(PROJECT_ROOT, file)}:${i - 3}-${i + 1}`);
            break;
          }
        } else {
          consecutive = 0;
        }
      }
    }
    expect(violations, `Large comment blocks found:\n${violations.join('\n')}`).toHaveLength(0);
  });

  test('no duplicate imports in any file', () => {
    const violations = [];
    for (const file of srcFiles) {
      const content = fs.readFileSync(file, 'utf-8');
      const imports = content.match(/^import .+ from ['"][^'"]+['"];?$/gm) || [];
      const sources = imports.map(i => i.match(/from ['"]([^'"]+)['"]/)?.[1]).filter(Boolean);
      const dupes = sources.filter((s, i) => sources.indexOf(s) !== i);
      if (dupes.length > 0) {
        violations.push(`${path.relative(PROJECT_ROOT, file)}: duplicate imports from ${[...new Set(dupes)].join(', ')}`);
      }
    }
    expect(violations, violations.join('\n')).toHaveLength(0);
  });
});

describe('commit message style enforcement', () => {
  test('no AI/agent references in source comments', () => {
    const aiPatterns = [/\bClaude\b/, /\bAI agent\b/i, /\bautomated by\b/i, /\bgenerated by AI\b/i];
    const violations = [];
    const srcFiles2 = getSourceFiles(PROJECT_ROOT);
    for (const file of srcFiles2) {
      if (file.includes('/tests/')) continue;
      const content = fs.readFileSync(file, 'utf-8');
      for (const pattern of aiPatterns) {
        if (pattern.test(content)) {
          violations.push(`${path.relative(PROJECT_ROOT, file)}: matches ${pattern}`);
        }
      }
    }
    expect(violations, violations.join('\n')).toHaveLength(0);
  });
});
